name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
    #Ejecutar pruebas unitarias
      - name: Run unit tests
        run: python -m unittest discover -s test  
    
    #Construir la imagen
      - name: Build Docker image
        run: docker build -t app_image:1.0 .

    #Ejecutar la imagen Docker
      - name: Run Docker container
        run: docker run -d -p 8000:8000 app_image:1.0

    #Ejecutar pruebas de integración
      - name: Run integration tests
        run: |
            if sh integration_testing/curl_testing.sh; then
                echo "Integration tests passed"
            else
                echo "Integration tests failed, but continuing with the workflow..."
            fi

    #Login y Empujar la imagen a DokerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag Docker image
        run: docker tag app_image:1.0.0 app_training_1:1.0

      - name: Push Docker image
        run: |
            docker push fabiocajamarca/app_training_1:1.0
